go-blogs/Controllers/AkunController.cs
using go_blogs.Helper;
using go_blogs.Models;
using go_blogs.Services.BlogServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace go_blogs.Controllers
{
    public class AkunController : Controller
    {
        private readonly AppDbContext _context;
        private readonly EmailServices _email;
        public AkunController(AppDbContext context,EmailServices e)
        {
            _context = context;//_Context dimasukan konstruktor agar lebih ringkas
            _email = e;
        }
        public IActionResult Daftar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Daftar(User datanya)
        {
            int OTP = BanyakBantuan.BuatOTP();

            _email.KirimEmail(datanya.Email, "Konfirmasi Daftar", "<h1 style='color:green'>Ini Dari Saya</h1>"+OTP);

            var deklarRole = _context.Tb_Roles.Where(x=>x.Id=="1").FirstOrDefault();
            datanya.Roles = deklarRole;
            _context.Add(datanya);//sama saja dengan insert into tb_User
             _context.SaveChanges();// eksekusi

            //cara 1
            return RedirectToAction("Masuk");//menarik ke action
            //cara 2
            //return RedirectToAction(controllerName: "Akun" actionName: "Masuk"); 
        }

        public IActionResult Masuk()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Masuk(User datanya)
        {
           
            //var cari = _context.Tb_User.Where(bebas =>  //proses pencarian
            //                                  bebas.Username == datanya.Username
            //                                  &&
            //                                  bebas.Password == datanya.Password
            //).FirstOrDefault();//hanya dapat 1 data

            var cariusername = _context.Tb_User.Where(bebas =>  //proses pencarian
                                               bebas.Username == datanya.Username
             ).FirstOrDefault();
            var caripassword = _context.Tb_User.Where(bebas =>  //proses pencarian
                                               bebas.Password == datanya.Password
             ).FirstOrDefault();

            if (cariusername != null)
            {
                var cekpassword= _context.Tb_User.Where(bebas =>  //proses pencarian
                                               bebas.Username == datanya.Username
                                               &&
                                               bebas.Password == datanya.Password
                                               )
                .Include(bebas2=>bebas2.Roles).FirstOrDefault();

                if (cekpassword != null)
                {
                    //proses tampungan data 
                    var daftar = new List<Claim>
                    {
                        new Claim("Username",cariusername.Username),
                        new Claim("Role",cariusername.Roles.Name)
                    };
                    //proses daftar auth
                    await HttpContext.SignInAsync(
                        new ClaimsPrincipal(
                            new ClaimsIdentity(daftar, "Cookie", "Username", "Role")
                        )
                   );
                    if (cariusername.Roles.Id == "1")//admin
                    {
                        //return RedirectToAction(controllerName: "Blog", actionName: "Index
                        return Redirect("/Admin/Home");
                    }else if(cariusername.Roles.Id == "2")
                    {
                        return Redirect("/User/Home");
                    }
                    return RedirectToAction(controllerName: "Home", actionName: "Privacy");
                }
                ViewBag.pesan = "password salah";
                return View(datanya);
            }
            ViewBag.pesan = "Username salah";
            return View(datanya);

            //if (cari != null)
            //{
            //    return RedirectToAction(controllerName: "Blog", actionName:"Index");
            //}
            //return View(datanya);

        }
        
        //tugas
        //cari tahu kalu misal username dan password tidak tersedia
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }


    }
}

go-blogs/Controllers/BlogController.cs
using go_blogs.Helper;
using go_blogs.Models;
using go_blogs.Services.BlogServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace go_blogs.Controllers
{
    //construktor=fungsi yang dijalankan pertama kali

    [Authorize]
    public class BlogController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IBlogServices _serv;
        public BlogController(AppDbContext context,IBlogServices serv)
        {
            _context = context;//_Context dimasukan konstruktor agar lebih ringkas
            _serv = serv;
        }

        public IActionResult Index()
        {
            var banyakdata = new BlogDashboard();

            banyakdata.blog = _context.Tb_blog.Include(x => x.User).ToList();

            banyakdata.user = _context.Tb_User.Include(x => x.Roles).ToList();

            return View(banyakdata);
            
        }

        public IActionResult Create()//UNTUK MENAMPILKAN HALAMAN YANG AKAN DIISI(kolom inputan)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Blog Parameter,IFormFile Image)//mnerima halaman yg akan diisi(inputan/proses)
        {
            //cara membut id
            //1.parameter.Id("contoh");
            //2.parameter.Id = Parameter.CreateDate.Ticks.ToString("x");

            //proses masukan ke database
            if (ModelState.IsValid)//untuk mengetahui suatu inputan itu valid atau tidak
            {
                //Parameter.Id = BuatPrimary.buatPrimary();cara memanggil file helper
                //string nama = User.GetUsername();
                //Parameter.User = _context.Tb_User.FirstOrDefault(x => x.Username == nama);//bagian service


                //_context.Add(Parameter);//mengganti dari insert into//bagian repository
                //await _context.SaveChangesAsync();// menyimpan perubahan

                //asalnya url https://localhost:5091
                //menjadi https://localhost:5091/home 
                await _serv.BuatBlog(Parameter, User.GetUsername(), Image);

                //return Ok(Parameter);
                return RedirectToAction("Index");
            }
            return View(Parameter); 
        }
        public IActionResult Details(int id)
        {

            var detail= new List<Blog>();
            var det= _context.Tb_blog.Where(x => x.Id == id).ToList();
            if (det == null)
            {
                return NotFound();
            }
            ViewBag.detail = det;
            return View();
        }
        public async Task<IActionResult> Ubah(int id)
        {
            //var cari = await _context.Tb_blog.FirstOrDefaultAsync(x => x.Id == id);
            var cari = await _serv.TampilBlogById(id);

            if (cari == null)
            {
                return NotFound();
            }

            return View(cari);
        }
        [HttpPost]
        public async Task<IActionResult> Ubah(Blog data)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Tb_blog.Update(data); // query update pada sql
                    //await _context.SaveChangesAsync(); // eksekusi update
                    await _serv.UpdateBlogAsync(data);
                }
                catch
                {
                    return NotFound();
                }

                return RedirectToAction("Index");
            }

            return View(data);
        }

        public async Task<IActionResult> Hapus(int id)
        {
            var cari = _context.Tb_blog.Where(x => x.Id == id).FirstOrDefault();
            if (cari == null)
            {
                return NotFound();
            }
            _context.Tb_blog.Remove(cari);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

go-blogs/Views/Shared/_Layout.cshtml
@using go_blogs.Helper;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - go_blogs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">go_blogs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="isi_biodata">Biodata</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Akun" asp-action="Daftar">Daftar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Admin/Home">Area Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/User/Home">Area User</a>
                        </li>
                    </ul>
                </div>
                <div>
                    @{
                        string cek = User.GetUsername();
                        if (cek !="")
                        {
                            <b>@User.GetUsername()</b>
                            
                            <a href="/Akun/Logout"  class="bi bi-box-arrow-right" style="color:rebeccapurple"
                               onclick="if (!confirm('yakin Untuk Keluar')) { return false;}">
                                Keluar
                            </a>
                        }

                    }



                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - go_blogs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

go-blogs/Views/Shared/_LayoutAkun.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Registration Page</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a asp-controller="Home" asp-action="Index">Go-Blogs</a>
        </div>

        <div class="card">
            <div class="card-body register-card-body">

                @RenderBody()
                @*memunculkan view kedalam tampilan*@
                

            </div>
            <!-- /.form-box -->
        </div><!-- /.card -->
    </div>
    <!-- /.register-box -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
</body>
</html>